// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package objectcomparatortest.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the ObjectComparatorTest module
	public static void aCT_ObjectComparatorAssertTrue(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("ObjectComparatorTest.ACT_ObjectComparatorAssertTrue").withParams(params).execute(context);
	}
	public static void aCT_ObjectComparatorFalse(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("ObjectComparatorTest.ACT_ObjectComparatorFalse").withParams(params).execute(context);
	}
	public static void aCT_ObjectComparatorFalseDifferentEntities(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("ObjectComparatorTest.ACT_ObjectComparatorFalseDifferentEntities").withParams(params).execute(context);
	}
	public static void aCT_ObjectComparatorFalseNoReference(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("ObjectComparatorTest.ACT_ObjectComparatorFalseNoReference").withParams(params).execute(context);
	}
	public static void aCT_ObjectComparatorFalseSimple(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("ObjectComparatorTest.ACT_ObjectComparatorFalseSimple").withParams(params).execute(context);
	}
	public static void aCT_ObjectComparatorTrueNoReference(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("ObjectComparatorTest.ACT_ObjectComparatorTrueNoReference").withParams(params).execute(context);
	}
}
